name: flutter_template
description: A Flutter template project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  logging: ^1.2.0
  intl: any
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  go_router: ^14.3.0
  flutter_displaymode: ^0.6.0
  flutter_animate: ^4.5.0
  material_color_generator: ^1.1.0
  reactive_forms: ^17.0.1
  dio: ^5.7.0
  persistent_bottom_nav_bar: ^6.2.1

  get_it: ^7.7.0
  get_it_mixin: ^4.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  fpdart: ^1.1.0
  bloc: ^8.1.4

  ngz_flutter_ui:
    git:
        url: https://github.com/anoguez/ngz_flutter_ui.git
        ref: 0.0.5

dev_dependencies:
  build_runner: ^2.4.11
  test: ^1.24.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  mockito: ^5.4.3
  bloc_test: ^9.1.7
  
  flutter_lints: ^4.0.0
  analyzer_plugin: ^0.11.3
  dart_code_metrics_presets: ^2.16.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
  adaptive_icon_background: "#FFFFFF"